version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "🤖 Dependencies"
    cooldown:
      exclude:
        - "github.com/gofiber/*"
        - "github.com/valyala/fasthttp*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "🤖 Dependencies"
